version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3309:3306 # HOST:CONTAINER
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=exrate
      - TZ=Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
